### ISSUE TITLE
We need to decide the database design

### ISSUE THREAD

**Issue by Abraham21** [synchronizedBroncos/zeitplan#17]
How should we design the database in mongodb? 1 collection for users with all info, or 2 collections with one for users and one for items, or 4 collections with one for users and three for each item type?

**Comment by alexliu108** [comment]
I think 4 collections would be better. It'll have a more distinct separation between the item types. I think that there should be 3 different objects for each item type, even though the data may be similar, the category is different. Also, I think itll be easier to manage when it scales.

**Comment by Abraham21** [comment]
{
 userId: string,
 userInfo: {},
 ttr: [{}],
 schedule: [{}],
 logs: [{}]
}
