### ISSUE TITLE
Add api calls to our anguarjs factory and learn how to call on them in front end

### ISSUE THREAD

**Issue by Abraham21** [synchronizedBroncos/zeitplan#24]
- AngularJS controller
- AngularJS factories
- Learn how it connects together so you can work with it

**Comment by excisionhd** [comment]
Have gotten a good understanding of how the factory and controllers work; will begin looking into making GET/POST requests to mongodb.

**Comment by excisionhd** [comment]
@Abraham21 
Should we close this issue or develop more or should I add more API calls?

**Comment by Abraham21** [comment]
We can close it. We have an understanding of how it works now.
