### ISSUE TITLE
Decide if we want our website to be a single page website

### ISSUE THREAD

**Issue by Abraham21** [synchronizedBroncos/zeitplan#26]
- Login page
- Register page
- Functionality page

**Comment by excisionhd** [comment]
Any updates?

Personally, I think that making this a SPA would be easier in terms of handling routes as well as make the website more interactive/responsive.  However, I am not sure about the login/register page.  

Thoughts?

**Comment by Abraham21** [comment]
Yes, let's make it a SPA. The only pages that would not be part of the single page would be the login/register, and possibly settings page.
