### ISSUE TITLE
Logs Page

### ISSUE THREAD

**Issue by cbdorado** [synchronizedBroncos/zeitplan#49]
We want to make sure that the "All", "Complete", and "Incomplete" buttons toggle on the log page

**Comment by alexliu108** [comment]
"TypeError: Cannot read property 'logs' of null" when no logs present

**Comment by excisionhd** [comment]
> "TypeError: Cannot read property 'logs' of null" when no logs present

This might have to do with the hardcoded user_id no longer being present (not sure if this has been removed from log-ctrl yet)
